$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    autoplay:2500,
    responsive:{
        0:{
            items:1
        },
        700:{
            items:1
        },
        900:{
            items:2
        },
        1000:{
            items:3
        }
    }
})